import React, { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import emailjs from '@emailjs/browser';
import { NavigationSection } from '../types';
export const Contact: React.FC = () => {
  const [form, setForm] = useState({ name: '', email: '', message: '' }); const [state, setState] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const service = import.meta.env.VITE_EMAILJS_SERVICE_ID; const template = import.meta.env.VITE_EMAILJS_TEMPLATE_ID; const key = import.meta.env.VITE_EMAILJS_PUBLIC_KEY; if (!service || !template || !key) { setState('Email configuration is not available. Please use the direct email link.'); return; } try { await emailjs.send(service, template, form, key); setState('Thank you - your message has been sent.'); setForm({ name: '', email: '', message: '' }); } catch { setState('Unable to send right now. Please use the direct email link.'); } };
  return <section id={NavigationSection.CONTACT} className="section-shell contact-section border-t border-[var(--color-rule)]"><div className="page-width contact-grid"><div><p className="eyebrow">Contact / 06</p><h2>Have a difficult problem <em>worth measuring?</em></h2><p>Open to internships, software-engineering and AI/ML roles, freelance work, research collaborations, and new opportunities where I can contribute and grow.</p><a className="text-link" href="mailto:youssefamenallah.contact@gmail.com">youssefamenallah.contact@gmail.com <ArrowUpRight size={16}/></a></div><form onSubmit={submit}><label>Name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({...form, email:e.target.value})}/></label><label>Message<textarea required rows={4} value={form.message} onChange={e => setForm({...form, message:e.target.value})}/></label><button className="button-solid" type="submit">Send note <ArrowUpRight size={17}/></button>{state && <p className="form-state">{state}</p>}</form></div></section>;
};
